(in-package :backgen)
(defun uniq (&rest inds)
  ;; (read-from-string (apply #'mkstr inds))
  (loop for i from 0 to (- (length inds) 1) 
     summing (* (expt 10000 (- (length inds) i 1)) (nth i inds)) into result 
     ;; summing (nth i inds) into result 
     finally (return result)))

;; (defmacro bool-entry (n fname name val)
;;   `(tl-forall i (tl-range ,n ,n)
;;      (tl-exists (entry stdlib-entries)
;;          (:stdlib-entry-id ,n :name ,(format nil "~a" (lower fname "")) :type "boolean" :body ,(format nil "function ~a(soggetto,sinistro,strict) {if (strict) { return \"(~a = ''~a'')\"; } else { return \"(~a = ''~a'' OR ~a IS NULL)\"; }}" (lower fname "") (upper name) (lower val) (upper name) (lower val) (upper name)))
;;        (tl-exists (par stdlib-entry-parameters) (:stdlib-entry-parameter-id (uniq i 1) :stdlib-entry-id ,n :name "soggetto" :type "soggetto"))
;;        (tl-exists (par stdlib-entry-parameters) (:stdlib-entry-parameter-id (uniq i 2) :stdlib-entry-id ,n :name "sinistro" :type "string")))))

;; (defmacro op-entry (n fname op)
;;   `(tl-forall i (tl-range ,n ,n)
;;      (tl-exists (entry stdlib-entries)
;;          (:stdlib-entry-id ,n :name  ,(format nil "~a" (lower fname "")) :type "string" :body,(format nil "function ~a(op1,op2,strict)
;; {if (strict) { return \"(\" + op1 + \" ~a \" + op2 + \"); } else { return \"((\" + op1 + \" ~a \" + op2 + \") OR (\" + op1 + \"IS NULL) OR (\" + op2 + \"IS NULL))\"; }}" (lower fname "") op op))

;;        (tl-exists (par stdlib-entry-parameters)
;;            (:stdlib-entry-parameter-id (uniq i 1) :stdlib-entry-id ,n :name "op1" :type "null"))
;;        (tl-exists (par stdlib-entry-parameters) (:stdlib-entry-parameter-id (uniq i 2) :stdlib-entry-id ,n :name "op2" :type "null")))))


(defun tl-oneof (&rest values)
  (nth (random (length values)) values))

;; (eval-when (:compile-toplevel :load-toplevel :execute)
;;   (defun tl-oneof (values)
;;     (nth (random (length values)) values)))


;; (eval-when (:compile-toplevel :load-toplevel :execute)
;;   (defun tl-someof (flags n val)
;;     (if (eql n 0)
;;         nil 
;;         (let ((flag (tl-oneof flags)))
;;           (apply #'list flag val (tl-someof (remove flag flags) (- n 1) val))))))

;; (defun sco1 (&key id days occurrences (date (get-universal-time)) (flag :d-flg-respons) (null 0))
;;   (let ((occurrences (- occurrences 1)))
;;     (labels ((sini (start end &optional val)
;;                (tl-forall i (tl-range start end)
;;                  (tl-exists (sini gv-ind-stat-sini) 
;;                      (:id-sini (uniq id i) :d-data-accad (tl-random-timestamp (- date (* days 86400)) date))
;;                    (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;                        (:id-sini (tl-retrieve :id-sini sini) :id-sogg id flag val)))))) 
;;       (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date))
;;         (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;             (:id-sini id :id-sogg id flag "1"))
;;         (sini 1 (- occurrences null) "1")
;;         (sini (1+ (- occurrences null)) occurrences)))))

;; (defun sco2 (&key id days occurrences (date (get-universal-time)) (flag :d-flg-respons) (null 0))
;;   (sco1 :id id :days days :occurrences occurrences :date date :flag flag :null null))

;; (defun sco3 (&key id days occurrences interval threshold (date (get-universal-time)) (flag :d-flg-respons) (null 0))
;;   (let ((occurrences (- occurrences 1)))
;;     (labels ((sini (start end &optional val)
;;                (tl-forall i (tl-range start end)
;;                  (tl-exists (sini gv-ind-stat-sini) 
;;                      (:id-sini (uniq id i) :d-data-accad (tl-random-timestamp (- date (* days 86400)) date) :m-num-lesi threshold)
;;                    (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;                        (:id-sini (tl-retrieve :id-sini sini) :id-sogg id flag val)))))) 
;;       (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date) :m-num-lesi threshold)
;;         (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;             (:id-sini id :id-sogg id flag "1"))
;;         (sini 1 (- occurrences null) "1")
;;         (sini (1+ (- occurrences null)) occurrences)))))

;; (defun sco4 (&key id days occurrences delay interval (date (get-universal-time)) (flag :d-flg-respons) (null 0))
;;   (let ((occurrences (- occurrences 1)))
;;     (labels ((sini (start end &optional val)
;;                (tl-forall i (tl-range start end)
;;                  (let* ((data-accad (- date (* i (/ days occurrences) 86400)))
;;                         (data-denun (+ data-accad (* delay 86400)))) 
;;                    (tl-exists (sini gv-ind-stat-sini) 
;;                        (:id-sini (uniq id i) :d-data-accad (tl-timestamp data-accad)
;;                                  :d-data-denun (tl-timestamp data-denun))
;;                      (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;                          (:id-sini (tl-retrieve :id-sini sini) :id-sogg id flag val))))))) 
;;       (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date) :d-data-denun (tl-timestamp (+ date (* delay 86400))))
;;         (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;             (:id-sini id :id-sogg id flag "1"))
;;         (sini 1 (- occurrences null) "1")
;;         (sini (1+ (- occurrences null)) occurrences)))))

;; (defun sco5 (&key id days occurrences delay interval (date (get-universal-time)) (flag :d-flg-respons) (null 0))
;;   (sco4 :id id :days days :occurrences occurrences :delay delay :interval interval :date date :flag flag :null null))

;; (defun sco6 (&key id days occurrences (date (get-universal-time)) (null 0))
;;   (sco1 :id id :days days :occurrences occurrences :date date :flag :d-flg-testimone :null null))

;; (defun sco7 (&key id (date (get-universal-time)) inv)
;;   (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date))
;;         (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;             (:id-sini id :id-sogg id :d-flg-conducente "1" :d-flg-patente-invalida inv))))

;; (defun sco8 (&key id days occurrences (date (get-universal-time)) (null 0))
;;   (sco1 :id id :days days :occurrences occurrences :date date :flag :d-flg-leso :null null))


;; (defun sco9 (&key id days occurrences (date (get-universal-time)) (flag :d-flg-respons) (null 0))
;;   (let ((occurrences (- occurrences 1)))
;;     (labels ((sini (start end &optional val)
;;                (tl-forall i (tl-range start end)
;;                  (tl-exists (sini gv-ind-stat-sini) 
;;                      (:id-sini (uniq id i) :d-data-accad (tl-random-timestamp (- date (* days 86400)) date))
;;                    (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;                        (:id-sini (tl-retrieve :id-sini sini) :id-sogg id flag val :m-num-rich-fgvs 1)))))) 
;;       (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date))
;;         (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;             (:id-sini id :id-sogg id flag "1" :m-num-rich-fgvs 1))
;;         (sini 1 (- occurrences null) "1")
;;         (sini (1+ (- occurrences null)) occurrences)))))

;; (defun sco10 (&key id (date (get-universal-time)) nveic)
;;   (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date))
;;         (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;             (:id-sini id :id-sogg id :d-tipo-sogg "p" :d-flg-proprietario "1" :m-num-veic nveic))))

;; (defun vei1 (&key id days occurrences (date (get-universal-time)))
;;   (let ((occurrences (- occurrences 1)))
;;     (labels ((sini (start end &optional val)
;;                (tl-forall i (tl-range start end)
;;                  (tl-exists (sini gv-ind-stat-sini) 
;;                      (:id-sini (uniq id i) :d-data-accad (tl-random-timestamp (- date (* days 86400)) date))
;;                    (tl-exists (veic gv-ind-stat-trg-veic-sini) 
;;                        (:id-sini (tl-retrieve :id-sini sini) :id-targa id)))))) 
;;       (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date))
;;         (tl-exists (veic gv-ind-stat-trg-veic-sini) 
;;             (:id-sini id :id-targa id))
;;         (sini 1 occurrences)))))

;; (defun vei2 (&key id days occurrences (date (get-universal-time)))
;;   (vei1 :id id :days days :occurrences occurrences :date date))

;; (defun vei3 (&key id days occurrences threshold (date (get-universal-time)) (null 0))
;;   (let ((occurrences (- occurrences 1)))
;;     (labels ((sini (start end &optional val)
;;                (tl-forall i (tl-range start end)
;;                  (tl-exists (sini gv-ind-stat-sini) 
;;                      (:id-sini (uniq id i) :d-data-accad (tl-random-timestamp (- date (* days 86400)) date) :m-num-lesi val)
;;                    (tl-exists (veic gv-ind-stat-trg-veic-sini) 
;;                        (:id-sini (tl-retrieve :id-sini sini) :id-targa id)))))) 
;;       (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date) :m-num-lesi threshold)
;;         (tl-exists (veic gv-ind-stat-trg-veic-sini) 
;;             (:id-sini id :id-targa id))
;;         (sini 1 (- occurrences null) threshold)
;;         (sini (1+ (- occurrences null)) occurrences)))))

;; (defun vei4 (&key id days occurrences delay interval (date (get-universal-time)) (null 0))
;;   (let ((occurrences (- occurrences 1)))
;;     (labels ((sini (start end &optional val)
;;                (tl-forall i (tl-range start end)
;;                  (let* ((data-accad (- date (* i (/ days occurrences) 86400)))
;;                         (data-denun (+ data-accad (* delay 86400)))) 
;;                    (tl-exists (sini gv-ind-stat-sini) 
;;                        (:id-sini (uniq id i) :d-data-accad (tl-timestamp data-accad)
;;                                  :d-data-denun (if val (tl-timestamp data-denun)))
;;                      (tl-exists (veic gv-ind-stat-trg-veic-sini) 
;;                          (:id-sini (tl-retrieve :id-sini sini) :id-targa id))))))) 
;;       (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date) :d-data-denun (tl-timestamp (+ date (* delay 86400))))
;;         (tl-exists (veic gv-ind-stat-trg-veic-sini) 
;;             (:id-sini id :id-targa id))
;;         (sini 1 (- occurrences null) t)
;;         (sini (1+ (- occurrences null)) occurrences)))))

;; (defun vei5 (&key id days occurrences (date (get-universal-time)) (null 0))
;;   (let ((occurrences (- occurrences 1)))
;;     (labels ((sini (start end &optional val)
;;                (tl-forall i (tl-range start end)
;;                  (tl-exists (sini gv-ind-stat-sini) 
;;                      (:id-sini (uniq id i) :d-data-accad (tl-random-timestamp (- date (* days 86400)) date))
;;                    (tl-exists (veic gv-ind-stat-trg-veic-sini) 
;;                        (:id-sini (tl-retrieve :id-sini sini) :id-targa id :m-num-rich-fgvs val)))))) 
;;       (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date))
;;         (tl-exists (veic gv-ind-stat-trg-veic-sini) 
;;             (:id-sini id :id-targa id :m-num-rich-fgvs 1))
;;         (sini 1 (- occurrences null) 1)
;;         (sini (1+ (- occurrences null)) occurrences)))))

;; (defun vei6 (&key id (date (get-universal-time)) inv)
;;   (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date))
;;         (tl-exists (veic gv-ind-stat-trg-veic-sini) 
;;             (:id-sini id :id-targa id :d-flg-targa-incoerente inv))))

;; (defun vei7 (&key id (date (get-universal-time)) inv)
;;   (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad (tl-timestamp date))
;;         (tl-exists (veic gv-ind-stat-trg-veic-sini) 
;;             (:id-sini id :id-targa id :d-flg-targa-inesistente inv))))

(defun vei8 (&key id (date (get-universal-time)) nyears)
  (tl-exists (sini gv-ind-stat-sini) 
      (:id-sini id :d-data-accad (tl-timestamp date))
    (tl-exists (veic gv-ind-stat-trg-veic-sini) 
        (:id-sini id :id-targa id :m-anni-immatr nyears))))

(defun vei9 (&key id days occurrences (date (get-universal-time)) (null 0))
  (let ((occurrences (- occurrences 1)))
    (labels ((sini (start end &optional val)
               (tl-forall i (tl-range start end)
                 (tl-exists (sini gv-ind-stat-sini) 
                     (:id-sini (uniq id i) :d-data-accad (tl-random-timestamp (- date (* days 86400)) date))
                   (tl-exists (veic gv-ind-stat-trg-veic-sini) 
                       (:id-sini (tl-retrieve :id-sini sini) :id-targa id :m-num-incoerenze val)))))) 
      (tl-exists (sini gv-ind-stat-sini) 
          (:id-sini id :d-data-accad (tl-timestamp date))
        (tl-exists (veic gv-ind-stat-trg-veic-sini) 
            (:id-sini id :id-targa id :m-num-incoerenze 1))
        (sini 1 (- occurrences null) 1)
        (sini (1+ (- occurrences null)) occurrences)))))

(defun vei10 (&key id (date (get-universal-time)) frm)
  (tl-exists (sini gv-ind-stat-sini) 
          (:id-sini id :d-data-accad (tl-timestamp date))
(s (sogg gv-ind-stat-sogg-sini) 
            (:id-sini id :id-sogg id :d-flg-veic-fermo-admin frm))))

(defun con1 (&key id days occurrences decor scad (date (get-universal-time)) (null 0))
  (let ((occurrences (- occurrences 1)))
    (labels ((sini (start end &optional val)
               (tl-forall i (tl-range start end)
                 (tl-exists (sini gv-ind-stat-sini) 
                     (:id-sini (uniq id i) :d-data-accad (tl-random-timestamp (- date (* days 86400)) date))
                   (tl-exists (sogg gv-ind-stat-sogg-sini) 
                       (:id-sini (tl-retrieve :id-sini sini) :id-sogg id :d-flg-contraente "1" :m-gg-da-decorrenza decor :m-gg-a-scadenza val)))))) 
      (tl-exists (sini gv-ind-stat-sini) 
          (:id-sini id :d-data-accad (tl-timestamp date))
        (tl-exists (sogg gv-ind-stat-sogg-sini) 
            (:id-sini id :id-sogg id :d-flg-contraente "1" :m-gg-da-decorrenza decor :m-gg-a-scadenza scad))
        (sini 1 (- occurrences null) scad)
        (sini (1+ (- occurrences null)) occurrences)))))

;; (defdb 
;;   (vei1 :id 1101 :days 180 :occurrences 3)
;;   (vei1 :id 1102 :days 180 :occurrences 2)

;;   (vei2 :id 1201 :days 180 :occurrences 3)
;;   (vei2 :id 1202 :days 180 :occurrences 2)

;;   (vei3 :id 1301 :days 180 :threshold 3 :occurrences 3)
;;   (vei3 :id 1302 :days 180 :threshold 3 :occurrences 2)
;;   (vei3 :id 1303 :days 180 :threshold 3 :occurrences 3 :null 1)

;;   (vei4 :id 1401 :days 180 :occurrences 3 :delay 10 :interval 180)
;;   (vei4 :id 1402 :days 180 :occurrences 2 :delay 10 :interval 180)
;;   (vei4 :id 1403 :days 180 :occurrences 3 :delay 10 :interval 180 :null 1)
  
;;   (vei5 :id 1501 :days 180 :occurrences 3)
;;   (vei5 :id 1502 :days 180 :occurrences 2)
;;   (vei5 :id 1503 :days 180 :occurrences 3 :null 1)

;;   (vei6 :id 1601 :inv "1")
;;   (vei6 :id 1602 :inv "0")
;;   (vei6 :id 1603)
  
;;   (vei7 :id 1701 :inv "1")
;;   (vei7 :id 1702 :inv "0")
;;   (vei7 :id 1703)

;;   (vei8 :id 1801 :nyears 2)
;;   (vei8 :id 1802 :nyears 1)
;;   (vei8 :id 1803)

;;   (vei9 :id 1901 :days 180 :occurrences 3)
;;   (vei9 :id 1902 :days 180 :occurrences 2)
;;   (vei9 :id 1903 :days 180 :occurrences 3 :null 1) 

;;   (vei10 :id 2001 :frm "1")
;;   (vei10 :id 2002 :frm "0")
;;   (vei10 :id 2003)

;;   (sco1 :id 101 :days 180 :occurrences 3)
;;   (sco1 :id 102 :days 180 :occurrences 2)
;;   (sco1 :id 103 :days 180 :occurrences 3 :null 1)

;;   (sco2 :id 201 :days 180 :occurrences 3)
;;   (sco2 :id 202 :days 180 :occurrences 2)
;;   (sco2 :id 203 :days 180 :occurrences 3 :null 1) 

;;   (sco3 :id 301 :days 180 :occurrences 3 :threshold 3 :interval 180)
;;   (sco3 :id 302 :days 180 :occurrences 2 :threshold 3 :interval 180)
;;   (sco3 :id 303 :days 180 :occurrences 3 :threshold 3 :interval 180 :null 1)

;;   (sco4 :id 401 :days 180 :occurrences 3 :delay 10 :interval 180)
;;   (sco4 :id 402 :days 180 :occurrences 2 :delay 10 :interval 180)
;;   (sco4 :id 403 :days 180 :occurrences 3 :delay 10 :interval 180 :null 1)
  
;;   (sco5 :id 501 :days 180 :occurrences 3 :delay 10 :interval 180)
;;   (sco5 :id 502 :days 180 :occurrences 2 :delay 10 :interval 180)
;;   (sco5 :id 503 :days 180 :occurrences 3 :delay 10 :interval 180 :null 1)

;;   (sco6 :id 601 :days 180 :occurrences 3)
;;   (sco6 :id 602 :days 180 :occurrences 2)
;;   (sco6 :id 603 :days 180 :occurrences 3 :null 1)

;;   (sco7 :id 701 :inv "1")
;;   (sco7 :id 702 :inv "0")
;;   (sco7 :id 703)
  
;;   (sco8 :id 801 :days 180 :occurrences 3)
;;   (sco8 :id 802 :days 180 :occurrences 2)
;;   (sco8 :id 803 :days 180 :occurrences 3 :null 1)
  
;;   (sco9 :id 901 :days 180 :occurrences 3)
;;   (sco9 :id 902 :days 180 :occurrences 2)
;;   (sco9 :id 903 :days 180 :occurrences 3 :null 1)

;;   (sco10 :id 1001 :nveic 2)
;;   (sco10 :id 1002 :nveic 1)
;;   (sco10 :id 1003)

;;   (con1 :id 2101 :days 180 :occurrences 3 :decor 10 :scad 10)
;;   (con1 :id 2102 :days 180 :occurrences 2 :decor 10 :scad 10)
;;   (con1 :id 2103 :days 180 :occurrences 3 :decor 10 :scad 10 :null 1))


;; (defdb 
;;   (tl-forall i (tl-range 1 10000)
;;     (tl-exists (wl white-list) 
;;         (:id i :id-elemento-white (* 2 i) :ultimo-agg (tl-timestamp (get-universal-time)) :tags nil :flg-white-list "s" :tipo-white (tl-oneof (list "soggetto" "targa")))
;;       )))

;; (pprint (sco9 :id 901 :days 180 :occurrences 3))

;; (defun sco0 (&key id days occurrences (date (get-universal-time)) (flag :d-flg-respons) (null 0))
;;   (let ((occurrences (- occurrences 1)))
;;     (labels ((sini (start end &optional val)
;;                (tl-forall i (tl-range start end)
;;                  (tl-exists (sini gv-ind-stat-sini) 
;;                      (:id-sini (uniq id i) :d-data-accad (random-date (- date (* days 86400)) date))
;;                    (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;                        (:id-sini (tl-retrieve :id-sini sini) :id-sogg id flag val)))))) 
;;       (tl-exists (sini gv-ind-stat-sini) 
;;           (:id-sini id :d-data-accad date)
;;         (tl-exists (sogg gv-ind-stat-sogg-sini) 
;;             (:id-sini id :id-sogg id flag t))
;;         (sini 1 (- occurrences null) t)
;;         (sini (1+ (- occurrences null)) occurrences)))))

(defun lify (value)
  (cond ((numberp value) value)
        ((equal "1" value) "1")
        ((equal "0" value) "0")
        ((listp value) (car value))
        ((t (error "value ~a not well typed" value)))))

(defun flatten-db (db)
  (let ((tables (remove-duplicates (mapcar #'car db))))
    (values-list (mapcar (lambda (table)
                           (mapcar (lambda (plst)
                                     (apply #'append (mapcar (lambda (pair)
                                                               (list (car pair) (lify (cadr pair))))
                                                             (group plst 2)))) 
                                   (mapcar #'cadr 
                                           (remove-if-not (lambda (elem) 
                                                            (eql (car elem) table))
                                                          db))))
                         tables))))

(defmacro coinvolto-diretto (strict)
  `(or (coinvolto ,strict)
       (leso ,strict)
       (richiedente ,strict)
       (proprietario ,strict)
       (contraente ,strict)
       (deceduto ,strict)
       (testimone ,strict)
       (responsabile ,strict)))

(defun random-sogg (&key id days (lesi 0) (delay) (fgvs 0) occurrences (decorr 0) (scad 0) (nveic 0) (date (get-universal-time)))
  (labels ((sini (start end)
             (tl-forall i (tl-range start end)
               (let* ((data-accad (random-date  (- date (* days 86400)) date))
                      (data-denun (random-date  data-accad (+ data-accad (* delay 86400)))))
                 (tl-exists (sini gv-ind-stat-sini) 
                     (:id-sini (uniq id i) :d-data-accad (tl-timestamp data-accad)
                               :d-data-denun (tl-timestamp data-denun)
                               :m-num-lesi (random-number 0 lesi))
                   (tl-exists (sogg gv-ind-stat-sogg-sini) 
                       (:id-sini (tl-retrieve :id-sini sini) :id-sogg id 
                                 :d-flg-richiedente (tl-oneof nil "0" "1")
                                 :d-flg-contraente (tl-oneof nil "0" "1")
                                 :d-flg-conducente (tl-oneof nil "0" "1")
                                 :d-flg-trasportato (tl-oneof nil "0" "1")
                                 :d-flg-pedone (tl-oneof nil "0" "1")
                                 :d-flg-leso (tl-oneof nil "0" "1")
                                 :d-flg-deceduto (tl-oneof nil "0" "1")
                                 :d-flg-testimone (tl-oneof nil "0" "1")
                                 :d-flg-medico (tl-oneof nil "0" "1")
                                 :d-flg-legale (tl-oneof nil "0" "1")
                                 :d-flg-carrozziere (tl-oneof nil "0" "1")
                                 :d-flg-respons (tl-oneof nil "0" "1")
                                 :d-flg-beneficiario (tl-oneof nil "0" "1")
                                 :d-flg-patente-invalida (tl-oneof nil "0" "1")
                                 :m-num-rich-fgvs (random-number 0 fgvs)
                                 :m-gg-a-scadenza (random-number 0 scad)
                                 :m-gg-da-decorrenza (random-number 0 decorr)
                                 :m-num-veic (random-number 0 nveic)))))))) 
    (let* ((data-accad date)
           (data-denun (random-date  data-accad (+ data-accad (* delay 86400)))))
      (tl-exists (sini gv-ind-stat-sini) 
          (:id-sini id :d-data-accad (tl-timestamp data-accad)
                    :d-data-denun (tl-timestamp data-denun)
                    :m-num-lesi (random-number 0 lesi))
        (tl-exists (sogg gv-ind-stat-sogg-sini) 
            (:id-sini id :id-sogg id 
                                
                      :d-flg-richiedente (tl-oneof nil "0" "1")
                      :d-flg-contraente (tl-oneof nil "0" "1")
                      :d-flg-trasportato (tl-oneof nil "0" "1")
                      :d-flg-pedone (tl-oneof nil "0" "1")
                      :d-flg-leso (tl-oneof nil "0" "1")
                      :d-flg-deceduto (tl-oneof nil "0" "1")
                      :d-flg-testimone (tl-oneof nil "0" "1")
                      :d-flg-medico (tl-oneof nil "0" "1")
                      :d-flg-legale (tl-oneof nil "0" "1")
                      :d-flg-carrozziere (tl-oneof nil "0" "1")
                      :d-flg-respons (tl-oneof nil "0" "1")
                      :d-flg-beneficiario (tl-oneof nil "0" "1")
                      :d-flg-conducente (tl-oneof nil "0" "1")
                      :d-flg-patente-invalida (tl-oneof nil "0" "1")
                      :m-num-rich-fgvs (random-number 0 fgvs)
                      :m-gg-a-scadenza (random-number 0 scad)
                      :m-gg-da-decorrenza (random-number 0 decorr)
                      :m-num-veic (random-number 0 nveic)))
        (sini 1 occurrences)))
    
    ;; (tl-exists (sini gv-ind-stat-sini) 
    ;;     (:id-sini id :d-data-accad (tl-timestamp date))
    ;;   (tl-exists (sogg gv-ind-stat-sogg-sini)
    ;;       (:id-sini id :id-sogg id))
    ;;   (sini 1 occurrences))
    ))

(defun random-veic (&key id days (lesi 0) (delay) (fgvs 0) (immatr 0) (incoer 0) occurrences (date (get-universal-time)))
  (labels ((sini (start end &optional val)
             (tl-forall i (tl-range start end)
               (let* ((data-accad (random-date  (- date (* days 86400)) date))
                      (data-denun (random-date  data-accad (+ data-accad (* delay 86400))))) 
                 (tl-exists (sini gv-ind-stat-sini) 
                     (:id-sini (uniq id i) :d-data-accad (tl-timestamp data-accad)
                               :d-data-denun (tl-timestamp data-denun)
                               :m-num-lesi (random-number 0 lesi))
                   (tl-exists (veic gv-ind-stat-trg-veic-sini) 
                       (:id-sini (tl-retrieve :id-sini sini) :id-targa id
                         
                                 :m-num-rich-fgvs (random-number 0 fgvs)
                                 
                                 
                                 :d-flg-veic-fermo-admin (tl-oneof nil "0" "1")
                                 :d-flg-targa-incoerente (tl-oneof nil "0" "1")
                                 :d-flg-targa-inesistente (tl-oneof nil "0" "1")
                                 :m-anni-immatr (tl-oneof (random-number 0 immatr) nil)
                                 :m-num-incoerenze (tl-oneof (random-number 0 incoer) nil)))))))) 
    (let* ((data-accad date)
           (data-denun (random-date  data-accad (+ data-accad (* delay 86400))))) 
      (tl-exists (sini gv-ind-stat-sini) 
          (:id-sini id :d-data-accad (tl-timestamp data-accad)
                    :d-data-denun (tl-timestamp data-denun)
                    :m-num-lesi (random-number 0 lesi))
        (tl-exists (veic gv-ind-stat-trg-veic-sini) 
            (:id-sini id :id-targa id
              
                      :m-num-rich-fgvs (random-number 0 fgvs)
                     

                      :d-flg-veic-fermo-admin (tl-oneof nil "0" "1")
                      :d-flg-targa-incoerente (tl-oneof nil "0" "1")
                      :d-flg-targa-inesistente (tl-oneof nil "0" "1")
                      :m-anni-immatr (tl-oneof (random-number 0 immatr) nil)
                      :m-num-incoerenze (tl-oneof (random-number 0 incoer) nil)))
        (sini 1 occurrences))) 


    ;; (tl-exists (sini gv-ind-stat-sini) 
    ;;     (:id-sini id :d-data-accad (tl-timestamp date))
    ;;   (tl-exists (veic gv-ind-stat-trg-veic-sini) 
    ;;       (:id-sini id :id-targa id))
    ;;   (sini 1 occurrences))
    ))

(indicatore test-sco1 (sinistro soggetto) (durata occorrenze)
  (cond ((ind-ge (cluster (sinistri-soggetto sinistro soggetto (coinvolto-diretto t))
                      durata)
             occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-soggetto sinistro soggetto (coinvolto-diretto nil)) 
                           durata)
                  occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-sco2 (sinistro soggetto) (durata occorrenze)
  (cond ((ind-ge (cluster (sinistri-soggetto sinistro soggetto (coinvolto-diretto t))
                      durata)
             occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-soggetto sinistro soggetto (coinvolto-diretto nil)) 
                           durata)
                  occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-sco3 (sinistro soggetto) (durata occorrenze lesi)
  (cond ((ind-ge (cluster (sinistri-soggetto sinistro soggetto (and (ind-ge (numerolesi t) lesi)
                                              (coinvolto-diretto t)))
                      durata)
             occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-soggetto sinistro soggetto (and (ind-ge (numerolesi nil) lesi)
                                              (coinvolto-diretto nil))) 
                           durata)
                  occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-sco4 (sinistro soggetto) (durata ritardo occorrenze)
  (cond ((ind-ge (cluster (sinistri-soggetto sinistro soggetto (and (ind-ge (let ((val (ind-minus (datadenuncia t 86400) (dataaccadimento t 86400))))
                                                                              (pprint `(case strict ,sinistro ,soggetto ,val))) ritardo)
                                                                    (coinvolto-diretto t)))
                          durata) 
                 occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-soggetto sinistro soggetto (and (ind-ge (let ((val (ind-minus (datadenuncia nil 86400) (dataaccadimento nil 86400))))
                                                                                   (pprint `(case loose ,sinistro ,soggetto ,val)))

                                                                                 ;; (ind-minus (datadenuncia nil 86400) (dataaccadimento nil 86400))
                                                                                 ritardo)
                                                                         (coinvolto-diretto nil))) 
                               durata)
                      occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-sco5 (sinistro soggetto) (durata ritardo occorrenze)
  (cond ((ind-ge (cluster (sinistri-soggetto sinistro soggetto (and (ind-ge (ind-minus (datadenuncia t) (dataaccadimento t)) ritardo)
                                                                    (coinvolto-diretto t)))
                          durata)
                 occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-soggetto sinistro soggetto (and (ind-ge (ind-minus (datadenuncia nil) (dataaccadimento nil)) ritardo)
                                                                         (coinvolto-diretto nil))) 
                               durata)
                      occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-sco6 (sinistro soggetto) (durata occorrenze)
  (cond ((ind-ge (cluster (sinistri-soggetto sinistro soggetto (testimone t))
                          durata)
                 occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-soggetto sinistro soggetto (testimone nil)) 
                               durata)
                      occorrenze)) (values nil t))
        (t (values nil nil))))



(indicatore test-sco8 (sinistro soggetto) (durata occorrenze)
  (cond ((ind-ge (cluster (sinistri-soggetto sinistro soggetto (leso t))
                          durata)
                 occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-soggetto sinistro soggetto (leso nil)) 
                               durata)
                      occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-sco9 (sinistro soggetto) (durata occorrenze)
  (cond ((ind-ge (cluster (sinistri-soggetto sinistro soggetto (and (ind-gt (numerofgvs t) 0)
                                                                    (coinvolto-diretto t)))
                          durata)
                 occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-soggetto sinistro soggetto (and (ind-gt (numerofgvs nil) 0)
                                                                         (coinvolto-diretto t))) 
                               durata)
                      occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-sco10 (sinistro soggetto) (soglia)
  (cond ((and (ind-match (car (field-values (soggetti sinistro soggetto) :d-tipo-sogg)) "p")
              (ind-match (car (field-values (soggetti sinistro soggetto) :d-flg-proprietario)) "1")
              (ind-ge (car (field-values (soggetti sinistro soggetto) :m-num-veic)) soglia)) (values t t)) 
        ((not (or (and (ind-match (car (field-values (soggetti sinistro soggetto) :d-tipo-sogg)) "p")
                       (ind-match (car (field-values (soggetti sinistro soggetto) :d-flg-proprietario)) "1")
                       (ind-ge (car (field-values (soggetti sinistro soggetto) :m-num-veic)) soglia))
                  (null (car (field-values (soggetti sinistro soggetto) :d-tipo-sogg)))
                  (null (car (field-values (soggetti sinistro soggetto) :d-flg-properietario)))
                  (null (car (field-values (soggetti sinistro soggetto) :m-num-veic))))) (values nil t))
        (t (values nil nil))))


(indicatore test-vei1 (sinistro veicolo) (durata occorrenze)
  (cond ((ind-ge (cluster (sinistri-veicolo sinistro veicolo)
                      durata)
             occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-veicolo sinistro veicolo) 
                           durata)
                  occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-vei2 (sinistro veicolo) (durata occorrenze)
  (cond ((ind-ge (cluster (sinistri-veicolo sinistro veicolo)
                      durata)
             occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-veicolo sinistro veicolo) 
                           durata)
                  occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-vei3 (sinistro veicolo) (durata occorrenze lesi)
  (cond ((ind-ge (cluster (sinistri-veicolo sinistro veicolo (and (ind-ge (numerolesi t) lesi)))
                      durata)
             occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-veicolo sinistro veicolo (and (ind-ge (numerolesi nil) lesi))) 
                           durata)
                  occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-vei4 (sinistro veicolo) (durata ritardo occorrenze)
  (cond ((ind-ge (cluster (sinistri-veicolo sinistro veicolo (and (ind-ge (ind-minus (datadenuncia t) (dataaccadimento t)) (* ritardo 86400))))
                          durata)
                 occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-veicolo sinistro veicolo (and (ind-ge (ind-minus (datadenuncia nil) (dataaccadimento nil)) (* ritardo 86400)))) 
                               durata)
                      occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-vei5 (sinistro veicolo) (durata occorrenze)
  (cond ((ind-gt (cluster (sinistri-veicolo sinistro veicolo (and (ind-gt (numerofgvs t) 0)))
                          durata)
                 occorrenze) (values t t))
        ((not (ind-gt (cluster (sinistri-veicolo sinistro veicolo (and (ind-gt (numerofgvs nil) 0))) 
                               durata)
                      occorrenze)) (values nil t))
        (t (values nil nil))))

(indicatore test-vei6 (sinistro veicolo) ()
  (cond ((ind-match (car (field-values (veicoli sinistro veicolo) :d-flg-targa-incoerente)) "1") (values t t))
        ((not (or (ind-match (car (field-values (veicoli sinistro veicolo) :d-flg-targa-incoerente)) "1")
                  (null (car (field-values (veicoli sinistro veicolo) :d-flg-targa-incoerente))))) (values nil t))
        (t (values nil nil))))


(indicatore test-vei7 (sinistro veicolo) ()
  (cond ((ind-match (car (field-values (veicoli sinistro veicolo) :d-flg-targa-inesistente)) "1") (values t t))
        ((not (or (ind-match (car (field-values (veicoli sinistro veicolo) :d-flg-targa-inesistente)) "1")
                  (null (car (field-values (veicoli sinistro veicolo) :d-flg-targa-inesistente))))) (values nil t))
        (t (values nil nil))))

(indicatore test-vei8 (sinistro veicolo) (soglia)
  (cond ((ind-ge (car (field-values (veicoli sinistro veicolo) :m-anni-immatr)) soglia) (values t t))
        ((not (or (ind-ge (car (field-values (veicoli sinistro veicolo) :m-anni-immatr)) soglia)
                  (null (car (field-values (veicoli sinistro veicolo) :m-anni-immatr))))) (values nil t))
        (t (values nil nil))))

(indicatore test-vei9 (sinistro veicolo) (durata occorrenze)
  (cond ((ind-ge (cluster (sinistri-veicolo sinistro veicolo (ind-gt (numeroincoerenzeveicolo t) 0))
                          durata)
                 occorrenze) (values t t))
        ((not (ind-ge (cluster (sinistri-veicolo sinistro veicolo (or (ind-gt (numeroincoerenzeveicolo nil) 0)
                                                                      (null (numeroincoerenzeveicolo nil)))) 
                               durata)
                      occorrenze)) (values nil t))
        (t (values nil nil))))
;; (let ((db (random-sogg :id 1 :days 180 :occurr2ences (1+ (random 4))))) 
;;   (pprint db)
;;   (pprint (multiple-value-list (flatten-db db))))
(defmacro test-ind-sogg (id-ind id-sini id-sogg name &rest args)
  `(tl-exists (out test-results) 
       (:id-sogg ,id-sogg :id-ind ,id-ind :expected 
                 (multiple-value-bind (res found) 
                     (,name ,id-sini ,id-sogg ,@args) 
                   (if found (if res "1" "0"))))))

(defmacro test-ind-veic (id-ind id-sini id-veic name &rest args)
  `(tl-exists (out test-results) 
       (:id-targa ,id-veic :id-ind ,id-ind :expected 
                 (multiple-value-bind (res found) 
                     (,name ,id-sini ,id-veic ,@args) 
                   (if found (if res "1" "0"))))))

(defun split (lst)
  (loop for elem in lst
       collecting (car elem) into first
       collecting (cadr elem) into second
       finally (return (list first second))))

(let ((sogg-res (apply #'append (loop for i from 101 to 110 collect
                                     (let ((db (random-sogg :id i :days 180 :occurrences (1+ (random 6)) :lesi 5 :delay 20)))
                                       (multiple-value-bind (*sinistri-table* *soggetti-table*) 
                                           (flatten-db db) 
                                         (tl-and db
                                                 (test-ind-sogg 1 i i test-sco1 180 3)
                                                 (test-ind-sogg 2 i i test-sco2 180 3)
                                                 (test-ind-sogg 3 i i test-sco3 180 3 3)
                                                 (test-ind-sogg 4 i i test-sco4 180 10 3)
                                                 (test-ind-sogg 5 i i test-sco5 180 10 3)
                                                 (test-ind-sogg 6 i i test-sco6 180 3)
                                                 (test-ind-sogg 7 i i test-sco7)
                                                 (test-ind-sogg 8 i i test-sco8 180 3)
                                                 (test-ind-sogg 9 i i test-sco9 180 3)
                                                 (test-ind-sogg 10 i i test-sco10 2)))))))
      (veic-res (apply #'append (loop for i from 1000001 to 1000010 collect
                                     (let ((db (random-veic :id i :days 180 :occurrences (1+ (random 6)) :lesi 50 :delay 20 :fgvs 3 :immatr 10 :incoer 1)))
                                       (multiple-value-bind (*sinistri-table* *veicoli-table*) 
                                           (flatten-db db)
                                         ;; (pprint *veicoli-table*)
                                         ;; (pprint `(case ,i))
                                         ;; (pprint (sinistri-veicolo i i (or (ind-gt (numeroincoerenzeveicolo nil) 0)
                                         ;;                                   (null (numeroincoerenzeveicolo nil)))))
                                         ;; (pprint (multiple-value-list (test-vei9 i i 180 2)))
                                         ;; (pprint (veicoli i i))
                                         (tl-and db
                                                 (test-ind-veic 11 i i test-vei1 180 3)
                                                 (test-ind-veic 12 i i test-vei2 180 3)
                                                 (test-ind-veic 13 i i test-vei3 180 2 4)
                                                 (test-ind-veic 14 i i test-vei4 180 10 3)
                                                 (test-ind-veic 15 i i test-vei5 180 3)
                                                 (test-ind-veic 16 i i test-vei6)
                                                 (test-ind-veic 17 i i test-vei7)
                                                 (test-ind-veic 18 i i test-vei8 2)
                                                 (test-ind-veic 19 i i test-vei9 180 3))))))))
  (let ((filename "D:/Dati/Profili/m026980/workspace/app/src/main/resources/data.sql")) 
    (pprint filename)
    (write-file filename (tl-ddl (tl-and sogg-res veic-res)))))



