(in-package :gui)

(defprim abst (parameters element)
  (:pretty () (list 'abst (list :parameters (synth-all :pretty parameters) 
                                :element (synth :pretty element)))) 
  (:req (path namelist) (seq (normal "Elemento parametrico caratterizzato dai seguenti parametri:")
                    (tabular
                        (row (normal "Parametro") (normal "Tipo"))
                        (mapcar #'(lambda (par)
                                    (row (normal "~a" (synth :name par))
                                         (synth :latex-type (synth :type par))))
                                parameters))
                    (synth :req element path namelist)))
  (:brief (path namelist) (synth :req this path namelist))
  (:reqlist (path namelist) (synth :reqlist element path namelist))
  (:template () (synth :template element))
  (:controller () (ts-empty))
  (:components (father) (synth :components element father))
  (:routes (father) (synth :routes element father))
  (:ts-imports () (synth :ts-imports element))
  (:dependencies () (synth :dependencies element)))
