(in-package :gui)

(defprim label (expr)
  (:pretty () (list 'label (list :expr (synth :pretty expr))))
  (:req (*) (seq 
             (normal "Etichetta contenente la seguente espressione: ") 
             (synth :req expr)))
  (:brief (path) (synth :req this path))
  (:reqlist (*) nil)
  (:template () (html:label (synth :template expr)))
  (:controller () (ts-empty))
  (:components (*) nil)
  (:routes (*) nil)
  (:ts-imports () nil)
  (:dependencies () nil))
